### ISSUE TITLE
pth files with image embeddings are not being saved automatically

### ISSUE THREAD

**Issue by correiav** [varunagrawal/VQA#3]
Hi @varunagrawal !
First of all, many thanks for sharing your work!
I tried to compute the image embeddings by myself using:

`python preprocess_images.py mscoco/annotations/instances_train2014.json --root mscoco --split train --arch vgg16`

I can see from the progress bar that the computation is completed however for some reason the .pth file with the image embeddings is not created. Would you happen to know why? 

`100%|████████████████████████████████████████| 5174/5174 [36:47<00:00,  2.34it/s]`

Also, could you shed a light as to why use the `instances_train2014.json` while extracting the images' embeddings?

Thank you so much!

**Comment by varunagrawal** [comment]
Hi @correiav. Can you please check if the code is creating an `image_embeddings` directory? The embeddings should be saved there.

The reason I use the `instances_train2014.json` file is because that contains the image IDs and corresponding annotations which I record so that during model training, we know which image embedding corresponds to which image in the dataset.

**Comment by correiav** [comment]
Hi @varunagrawal! 
Yes, the code is creating the `image_embeddings` directory. The reason why the directory was not being created was because of the command on line 97 `exit(0)`, I just commented that and all worked perfectly. 
Thank you so much for coming back to me!

**Comment by correiav** [comment]
Haha, no problem. :). Thank you
